version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - docker/login:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
      - run: |
          echo "Building Docker image..."
          docker build -t $DOCKER_HUB_USERNAME/flask-docker-app:latest .
      - docker/push:
          image: $DOCKER_HUB_USERNAME/flask-docker-app:latest

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: muhdrmdhn/education-space:1.0.0
      - docker/push:
          image: muhdrmdhn/education-space:1.0.0


workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test          