version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Docker Build and Push
          command: |
            docker build -t muhdrmdhn/education-space .
            docker push muhdrmdhn/education-space

  deploy:
    docker:
        - image: cimg/node:16.10
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku stack:set container -a muhd-ramadhan-su-devops
                heroku container:push web -a muhd-ramadhan-su-devops
                heroku container:release web -a muhd-ramadhan-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish